apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: alon-bot-python-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alon-bot-python
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
