apiVersion: v1
kind: Pod
metadata:
  name: alon-bot-pod
  labels:
    alon-bot-pod: "true"
    some-label: some-label-value
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
  - name: alon-bot-python-deployment
    image: kubealon/alon-bot-python
  - name: alon-bot-nginx-deployment
    image: kubealon/alon-bot-nginx