replicaCount: 1

image:
  repository: kubealon/alon-bot-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
