apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alon-bot.fullname" . }}
  labels:
    {{- include "alon-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alon-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alon-bot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: alon-bot-data
              mountPath: /data
      volumes:
        - name: alon-bot-data
          persistentVolumeClaim:
            claimName: {{ include "alon-bot.fullname" . }}-pvc
