{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "alon-bot.fullname" . }}
  labels:
    {{- include "alon-bot.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "alon-bot.fullname" . }}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
{{- end }}

